apiVersion: batch/v1
kind: Job
metadata:
  name: kube-node-job-v2
spec:
  template:
    spec:
      volumes:
      - name: logs-storage
        persistentVolumeClaim:
          claimName: go-test-pvc
      containers:
        - name: kube-node-job
          image: nvovap/wb_node_job:v1
          command: ["npm",  "start"]
          volumeMounts:
          - mountPath: "/usr/src/app/logs"
            name: logs-storage
      restartPolicy: Never
  backoffLimit: 4




